### ISSUE TITLE
Optaplanner support?

### ISSUE THREAD

**Issue by sherl0cks** [apache/incubator-kie-examples#103]
There currently isn't an optaplanner example. Is there support in kogito/quarkus for optaplanner? If so, would you all be interested in a contribution that ports one of the examples in https://github.com/kiegroup/optaplanner/tree/master/optaplanner-examples to this repo?

**Comment by kmacedovarela** [comment]
Hey, please refer to this example: 

https://github.com/kiegroup/kogito-examples/pull/121

**Comment by r00ta** [comment]
Hi @sherl0cks , I close the issue given that we now have some OP examples
