### ISSUE TITLE
Google/Custom OIDC /OAuth2 setup with Kogito Dataindex and configuring graphql security without keycloak

### ISSUE THREAD

**Issue by doogle-oss** [apache/incubator-kie-examples#1058]
Hi Team,
In our organisation we use internal active directory and federation services. We do not manage via keycloak. Both Task Console and Management Console need keycloak setups. Is there any informaiton on how we can customize the same with quarkus security. Do we need to embedded our platfomr with that for the quarkus oidc or there is sample example to do this.

p.s. we cant use keycloak as our organisation have its own version of OAuth and OIDC setups. Please advise on this. Its blocking us from doing custom security.

**Comment by ricardozanini** [comment]
Duplicate issue: https://github.com/kiegroup/kogito-apps/issues/1178
