### ISSUE TITLE
Build of decisiontable-quarkus-example fails if you put a csv file into resources folder

### ISSUE THREAD

**Issue by dragondiver** [apache/incubator-kie-examples#1072]
My build breaks, if I put a simple csv file (containing 1;2;3) into the resources folder.
How could I use a decision table in a larger project, that also needs some csv files?

**Comment by mariofusco** [comment]
Unfortunately this is a well known issue of drools and therefore also of kogito that is based on it. If you have the decisiontables module among your dependencies then drools assumes that all files with extensions `.xls`, `.xlsx` and `.csv` under the folder `src/main/resources` are decisiontables, it tries to compile them as such and if it can't it raises a compile time error. We know that this assumption is too strong and are thinking how to fix this, for instance requiring for decisiontables an extension like `.drools.csv`, but in the meanwhile the only possible workaround is moving all .xls`, `.xlsx` and `.csv` files out of the `src/main/resources` folder.
