### ISSUE TITLE
Impossible to find field chronology in class java.time.LocalDate

### ISSUE THREAD

**Issue by Dantes-Damir** [apache/incubator-kie-examples#1103]
In project process-postgresql-persistence-springboot https://github.com/kiegroup/kogito-examples/tree/stable/kogito-springboot-examples/process-postgresql-persistence-springboot, i added variable java.time.LocalDate: private LocalDate localDate; in Traveller class:
`***
public class Traveller {

    private String firstName;
    private String lastName;
    private String email;
    private String nationality;
    private Address address;
    private LocalDate localDate;

    public Traveller() {

    }

    public Traveller(String firstName, String lastName, String email, String nationality, Address address, LocalDate localDate) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.nationality = nationality;
        this.address = address;
        this.localDate = localDate;
    }

    public LocalDate getLocalDate() {
        return localDate;
    }

    public void setLocalDate(LocalDate localDate) {
        this.localDate = localDate;
    }
***`
And i got this error: **Failed to execute goal org.kie.kogito:kogito-maven-plugin:1.15.0.Final:process-model-classes (default-process-model-classes) on project process-postgresql-persistence-springboot: Error during processing model classes: Error while generating proto for model class class org.acme.travels.Traveller Impossible to find field chronology in class java.time.LocalDate -> [Help 1]
[ERROR]**
logs : [logs.txt](https://github.com/kiegroup/kogito-examples/files/7950689/logs.txt)

**Comment by Dantes-Damir** [comment]
@evacchi @fjtirado Can you help me with this problem? Thanks.

**Comment by r00ta** [comment]
Hi @Dantes-Damir , can you try with the latest version 1.16.0?  If I'm not wrong, the fix should be already included in that release

**Comment by Dantes-Damir** [comment]
Hi @r00ta, i got the same error with 1.16.0  version
[logs.txt](https://github.com/kiegroup/kogito-examples/files/7950915/logs.txt)

**Comment by ricardozanini** [comment]
@cristianonicolai cc

**Comment by cristianonicolai** [comment]
@Dantes-Damir  the fix should land in version 1.18.0, feel free to reopen this if the problem persists.
