### ISSUE TITLE
Not able to use  LocalDateTime and ZonedDateTime  

### ISSUE THREAD

**Issue by anandgupta565** [apache/incubator-kie-examples#1118]
Hi,
Kogito  bom version:- 1.16.0.Final
Quarkus bom:- 2.7.0.Final
I have added ZonedDateTime and LocalDateTime in my model . but i am getting bellow error 

**Build step org.kie.kogito.quarkus.processes.depoyment.ProcessAssetsProcessor#postGenerationProcessing throw on exception ..
error generation proto for model Employee Cannot find info in janindex or short**

public class  Employee {

private String firstName;
private String lastName;
private String email;
private String nationality;
private Address address;
private ZonedDateTime  zoneDateTime;
private LocalDateTime localDatetime
}

After changing LocalDateTime,ZonedDateTime to Date .Code is working fine
Kindly let us know ,How can we use another datatype for date?

**Comment by doogle-oss** [comment]
Can you please advise what datatypes are available for use as process variables. We use Long, Integer, String, Date and boolean.

**Comment by doogle-oss** [comment]
@evacchi is there any specific setup for adding other datatypes.

**Comment by cristianonicolai** [comment]
@anandgupta565  the fix should land in version 1.18.0, feel free to reopen this if the problem persists.
