### ISSUE TITLE
Doesn't compile with latest mvn (3.9.0), and version listed in readme is incorrect

### ISSUE THREAD

**Issue by jbeuree** [apache/incubator-kie-examples#1576]
### Describe the bug

The README says maven version 3.8.1+ is required. Looks to actually be 3.8.6, but there are also problems going to 3.9.0.

Compiling with mvn version 3.8.3 demonstrates that the 3.8.1 minimum is incorrect:

> [INFO] ---------< org.kie.kogito.examples:process-springboot-example >---------
> [INFO] Building Kogito Example :: Process and Spring Boot 1.34.0.Final
> [INFO] --------------------------------[ jar ]---------------------------------
> [INFO]
> [INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ process-springboot-example ---
> [INFO] Deleting /home/jer/repo/kogito-examples/kogito-springboot-examples/process-springboot-example/target
> [INFO]
> [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-versions) @ process-springboot-example ---
> [WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message:
> Detected Maven Version: 3.8.3 is not in the allowed range 3.8.6.

Compiling with 3.9.0 is allowed, but results in a compile error locating a DirectoryScanner class that appears to be used by the impsort-maven-plugin.

The minimum needed, 3.8.6, does work. Haven't tried later 3.8 version to determine when it starts breaking. This was all tested on linux/ubuntu with jdk 11.

**Comment by radtriste** [comment]
@jbeuree Thank you for reporting.
We did not actually test it with Maven 3.9.0 yet ... This version is 2 weeks old. And if Maven broke things, we cannot anticipate that.

I see 2 issues in there:
- Outdated documentation, Maven version should be 3.8.x
- Test with Maven 3.9.x needs to be done and corrected.

We are currently using Maven 3.8.7 so it should work with that version.

**Comment by radtriste** [comment]
Created 2 issues:
- https://issues.redhat.com/browse/KOGITO-8704
- https://issues.redhat.com/browse/KOGITO-8705

**Comment by radtriste** [comment]
that should be corrected in 1.35.0.Final
