### ISSUE TITLE
A required class was missing while executing net.revelc.code:impsort-maven-plugin:1.5.0:sort: org/codehaus/plexus/util/DirectoryScanner

### ISSUE THREAD

**Issue by leesonwei** [apache/incubator-kie-examples#1579]
### Describe the bug

[INFO] --- impsort:1.5.0:sort (default) @ process-usertasks-quarkus-with-console ---
[INFO] Using compiler compliance level: JAVA_11
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  34.941 s
[INFO] Finished at: 2023-02-21T14:12:13+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.revelc.code:impsort-maven-plugin:1.5.0:sort (default) on project process-usertasks-quarkus-with-console: Execution default of goal net.revelc.code:impsort-maven-plugin:1.5.0:sort failed: A required class was missing while executing net.revelc.code:impsort-maven-plugin:1.5.0:sort: org/codehaus/plexus/util/DirectoryScanner
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>net.revelc.code:impsort-maven-plugin:1.5.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/root/.m2/repository/net/revelc/code/impsort-maven-plugin/1.5.0/impsort-maven-plugin-1.5.0.jar
[ERROR] urls[1] = file:/root/.m2/repository/com/github/javaparser/javaparser-core/3.18.0/javaparser-core-3.18.0.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>org.kie.kogito.examples:process-usertasks-quarkus-with-console:1.34.0.Final, parent: ClassRealm[maven.api, parent: null]]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] : org.codehaus.plexus.util.DirectoryScanner
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

### How to Reproduce?

1.git clone https://github.com/kiegroup/kogito-examples.git
2.cd kogito-examples/kogito-quarkus-examples/process-usertasks-quarkus-with-console
3.mvn clean compile

### Output of `uname -a` or `ver`

Linux master.anywhere.com 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

java version "17.0.6" 2023-01-17 LTS

### Kogito version or git rev (or at least Quarkus version if you are using Kogito via Quarkus platform BOM)

1.34.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.0

**Comment by fjtirado** [comment]
Already reported https://issues.redhat.com/browse/KOGITO-8704
