### ISSUE TITLE
Kogito Workflow not working with Mongo

### ISSUE THREAD

**Issue by tech-bee-10** [apache/incubator-kie-examples#1731]
### Describe the bug

I am trying out Kogito Serverless workflow and it is working as expected. I used persistence via Postgres to ensure in-progress workflow instances are able to continue by maintaining the current context in DB so that it can resume once it is back online. But when I try the same with MongoDB it is not working as expected. It is saving some info in DB but when the workflow instance is back online, it is not able to recognise the instance details and getting skipped.

### Expected behavior

MongoDB persistence to work same as that of feature provided for Postgres

### Actual behavior

Workflow instance not able to continue the flow when MongoDB is used but working fine when Postgres is used.

### How to Reproduce?

Added below dependency in pom.xml

```
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-persistence-mongodb</artifactId>
</dependency>
```

Added below properties:
```
kogito.persistence.type=mongodb
quarkus.mongodb.connection-string = mongodb://localhost:27017
quarkus.mongodb.database=kogito_db
```

All my workflow steps are async APIs using Kafka. For each step where Kafka message will be sent as part of async flow, there will be a wait for response step as part of workflow to wait for output from the async execution. The consumer for async message processing is put on pause to make the workflow instance execution go into wait state and stopped the workflow execution. When I async message processing and start the workflow app, it is able to continue from the previous state using Postgres by following this [documentation](https://sonataflow.org/serverlessworkflow/latest/persistence/persistence-with-postgresql.html). But when tried with Mongo, it is skipping the left out processing.

**Comment by radtriste** [comment]
Hi @rand-guy 
We did not test Kogito Serverless Workflow with MongoDB yet so it may be indeed not working ...
As you can read in the documentation, for now, we encourage to use Posgres.
We may in the future provide more persistence storage.

@cristianonicolai @ricardozanini anything to add ?

**Comment by tech-bee-10** [comment]
Got it. Thanks.
