### ISSUE TITLE
Kogito Serverless Workflow does not send the Cloud Event in binary mode

### ISSUE THREAD

**Issue by gpando** [apache/incubator-kie-examples#1738]
### Describe the bug

Kogito Serverless Workflow does not send the Cloud Event in binary mode (mode default).
Even when forcing the properties, it doesn't work:

`mp.messaging.outgoing.products.bootstrap.servers=localhost:9092
mp.messaging.outgoing.products.connector=smallrye-kafka
mp.messaging.outgoing.products.topic=productsworkflow
mp.messaging.outgoing.products.cloud-events=true
mp.messaging.outgoing.products.cloud-events-mode=binary`

### Expected behavior

View the properties of Cloud Events in the headers, not in the payload.

### Actual behavior

Cloud Events in the headers in payload

### How to Reproduce?

It occurs in any example.

**Comment by fjtirado** [comment]
Thats current expected behaviour. Kogito support consuming both binary and structure, but only publish on structure. Please open a Feature Request JIRA to add support for  binary publishing

**Comment by gpando** [comment]
[#3115](https://github.com/kiegroup/kogito-runtimes/issues/3115)
