### ISSUE TITLE
Async API with publish and subscribe operation

### ISSUE THREAD

**Issue by tech-bee-10** [apache/incubator-kie-examples#1742]
### Description

I am trying out implementing a Kogito serverless workflow where each stage involves async call to external system. Currently based on available documentation, I have used publish operation to send a Kafka event for async execution, but for response, I am using event wait trigger to wait for response. Could you provide an example where I can use same async API specification with publish and subscribe with correlation. This way, I can use same async API specification to describe publish and subscribe operations. Currently I couldn't find documentation for SUBSCRIBE as response for async API call.

**Comment by fjtirado** [comment]
@rand-guy 
This PR with the example we forgot to merge https://github.com/kiegroup/kogito-examples/pull/1536 
You can check a couple testing swf defintions  that can serve as example here 
https://github.com/kiegroup/kogito-runtimes/blob/main/quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/asyncConsumer.sw.json
and here
https://github.com/kiegroup/kogito-runtimes/blob/main/quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/asyncPublisher.sw.json
The test file give you an idea of how it is invoked
https://github.com/kiegroup/kogito-runtimes/blob/main/quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/AsyncAPIIT.java
The documentation is here
https://sonataflow.org/serverlessworkflow/latest/service-orchestration/orchestration-of-asyncapi-based-services.html
