### ISSUE TITLE
Examples that are using quay.io/kiegroup/kogito-runtime-jvm:latest generate it's own docker image are failing after Quarkus3 migration

### ISSUE THREAD

**Issue by nmirasch** [apache/incubator-kie-examples#1858]
### Describe the bug

- Examples that are using quay.io/kiegroup/kogito-runtime-jvm:latest generate it's own docker image are failing after Quarkus3 regarding that jdk update to 17.
It seems that image hadn't been published with the recently changes. 
- Quarkus 3 also introduced the security enabled by default: Is needed disable that  adding to that generated images:
# Security
quarkus.oidc.enabled=false
quarkus.oidc.tenant-enabled=false
quarkus.oidc.auth-server-url=none

**Comment by domhanak** [comment]
@LuboTerifaj FYI, you mentioned some work with examples recently

**Comment by wmedvede** [comment]
For the record, the serverless-workflow-timeouts-showcase-extended example was addressed here https://github.com/apache/incubator-kie-kogito-examples/pull/1857
