### ISSUE TITLE
serverless-workflow-hello-world example is referencing adoc in README.md

### ISSUE THREAD

**Issue by LuboTerifaj** [apache/incubator-kie-examples#1945]
### Describe the bug

[serverless-workflow-hello-world](https://github.com/apache/incubator-kie-kogito-examples/tree/main/serverless-workflow-examples/serverless-workflow-hello-world) example is referencing adoc in README.md

The variables are not resolved properly in the documentation. For example:
- As a developer, you can use {product_name}
- {java_min_version}
- {maven_min_version}
- {quarkus_cli_url}
- [Knative Workflow CLI](https://github.com/kiegroup/kogito-docs/blob/main/serverlessworkflow/modules/ROOT/pages/getting-started/testing-and-troubleshooting/kn-plugin-workflow-overview.adoc) {kn_cli_version}
- {product_name}
- etc.

In addition, there are references to https://github.com/kiegroup/kogito-docs instead of https://github.com/apache/incubator-kie-kogito-docs

### Expected behavior

The example either contains a guide how to use the example, or it is referencing well formatted document.

### Actual behavior

The referenced adoc document is not suited for final reading document. As a result, a user will end up with unresolved variables.

**Comment by domhanak** [comment]
The issue is obviously wrong URL in the README, fixed here - https://github.com/apache/incubator-kie-kogito-examples/pull/2029

**Comment by domhanak** [comment]
Also, the issue is reported against deprecated stable branch, that means the description is invalid. On main branch the fix is to update the URL to the quarkus getting started guide.

**Comment by domhanak** [comment]
Fixed by https://github.com/apache/incubator-kie-kogito-examples/pull/2029
