### ISSUE TITLE
DMN example in Doc does not work

### ISSUE THREAD

**Issue by sschwedler** [apache/incubator-kie-examples#276]
I tried the dmn example described here [1]. The age check example with the the dmn wrapped in a bpmn does not work. It fails with the following message. I tried the steps described and also copies the provided dmn and bpmn2 files.

> 2020-06-16 11:31:42,599 ERROR [org.kie.dmn.cor.imp.DMNRuntimeImpl] (executor-thread-63) Required dependency 'Person' not found on node 'isAdult'

[1] https://docs.jboss.org/kogito/release/latest/html_single/#chap-kogito-creating-running

**Comment by sschwedler** [comment]
User error :-)

**Comment by sterobin** [comment]
Thanks @sschwedler . I was going to guess a capitalization error or something. Glad you figured it out. Thanks for the bug anyway. :)
