### ISSUE TITLE
Quarkus mongoDB example is not generating proto files

### ISSUE THREAD

**Issue by ghost** [apache/incubator-kie-examples#390]
Hi,

I picked up process-mongodb-persistence-quarkus example and when I tried to build project its not generating proto files in target/classes/persistence directory. 

Here are my application.properties entries
```
kogito.persistence.type=mongodb
quarkus.mongodb.connection-string=mongodb://localhost:27017
quarkus.mongodb.database=kogito_db
```

Even service is creating default DB in mongoDB i.e. kogito. So seems somehow its not picking up `quarkus.mongodb.database`. Also if I change `kogito.persistence.type=mongodb` to `kogito.persistence.type=infinispan` it generate proto files but service doesn't get started (and that's the expected behaviour)

**Comment by r00ta** [comment]
Hi @rakeshim , with this PR that was merged few hours ago the proto files are generated also for Mongo https://github.com/kiegroup/kogito-runtimes/pull/825 . 

examples on `master` should not have anymore the bug you reported

**Comment by ghost** [comment]
It's great to see that it's fixed now and thanks for the update. I will have a look.
