### ISSUE TITLE
Wrong readme on optaplanner-flight example

### ISSUE THREAD

**Issue by chris-aeviator** [apache/incubator-kie-examples#397]
the readme states to POST `{ "passenger": { "name": "Amy Cole", "seatTypePreference": "WINDOW", "emergencyExitRowCapable": true, "paidForSeat": true, "seat": "3A" }}`

while src/main/java/org/kie/kogito/examples/domain/PassengerDTO.java does not require a "passenger" to be sent on `/flights/{id}/newPassengerRequest` and therefore only 

`{ "name": "Amy Cole", "seatTypePreference": "WINDOW", "emergencyExitRowCapable": true, "paidForSeat": true, "seat": "3A" }` should be posted

**Comment by r00ta** [comment]
Thanks @chris-aeviator and sorry for the late reply. I've checked and you're right. I just pushed the fix
