### ISSUE TITLE
Recommend maven-enforcer to validate maven version [Error injecting...]

### ISSUE THREAD

**Issue by dhartford** [apache/incubator-kie-examples#51]
Hi Team,
While trying the onboarding-examples, payroll project, ran into this issue and the following resolution by adding a maven-enforcer to the pom.xml.   Not sure if this is a path you want to go down, so simply recommending (it may be project specific, or add to parent).

     
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <version>3.0.0-M2</version>
        <executions>
          <execution>
            <id>enforce-maven</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <requireMavenVersion>
                  <version>3.5.2+</version>
                </requireMavenVersion>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>

**Comment by mswiderski** [comment]
for kogito you need to have maven 3.5.3+ as we align with quarkus on that

**Comment by mswiderski** [comment]
would you mind preparing PR for it?

**Comment by mswiderski** [comment]
PR merged
