### ISSUE TITLE
Decision Tables - Rules are not generated when removing Sample.drl

### ISSUE THREAD

**Issue by mmonti** [apache/incubator-kie-examples#53]
I am testing the ***drools-quarkus-example*** and I found that removing the Sample.drl file from the resources folder causes that the **kogito-maven-plugin** not generating the rules for the _CanDrink.xls_ decision table.

Adding an empty DRL file, it generates the rules again:

- With the DRL file on resources:
<img width="654" alt="Screen Shot 2019-07-22 at 11 27 46 AM" src="https://user-images.githubusercontent.com/680431/61652852-25b13680-ac76-11e9-813b-4e94e5c45b0c.png">

- Without the DRL on resources:
<img width="655" alt="Screen Shot 2019-07-22 at 11 30 02 AM" src="https://user-images.githubusercontent.com/680431/61652864-2cd84480-ac76-11e9-8387-6af500d25350.png">

**Comment by mswiderski** [comment]
moved to jira https://issues.jboss.org/browse/KOGITO-79
