### ISSUE TITLE
No class PMMLModelEvaluatorFinder od Mac

### ISSUE THREAD

**Issue by foogood7** [apache/incubator-kie-examples#543]
When I try to start `dmn-quarkus-example`, I got following error:

```terminal
2021-02-01 11:26:53,101 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.NoClassDefFoundError: org/kie/pmml/evaluator/core/executor/PMMLModelEvaluatorFinder
```

I followed your `README.md` file. What I need to do to start project successfully?

**Comment by foogood7** [comment]
That is some Java problem, I tried with AdoptOpenJDK, but I got:

```
Caused by: java.lang.ClassNotFoundException: org.kie.memorycompiler.resources.ResourceReader
```

Very strange.

**Comment by r00ta** [comment]
Hi @foogood7 , could you please provide us the following info? 
**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
 - are you using `master` branch or a particular release? 
 - Could you paste the full stacktrace?

**Comment by r00ta** [comment]
Hi @foogood7 , any update on this?

**Comment by r00ta** [comment]
Closing since there is no response from author. Feel free to re-open it adding more info
