### ISSUE TITLE
Running my dmn-quarkus-example with different rules

### ISSUE THREAD

**Issue by jiwonjoung** [apache/incubator-kie-examples#571]
Hello, 
I have run the dmn-quarkus-example for the traffic violation. I have created another dmn file with a small example of my own and I would like to run it using quarkus and drools. However, I get an error (below) when I modify the Traffic\ Violation.dmn file in the dmn-quarkus-example project. What is the correct way to test drools/quarkus with a custom dmn file? 

`{"namespace":"https://github.com/kiegroup/drools/kie-dmn/_A4BCA8B8-CF08-433F-93B2-A2598F19ECFF","modelName":"Traffic Violation","dmnContext":{"weather":{"status":"rain"}},"messages":[{"severity":"ERROR","message":"Required dependency 'Violation' not found on node 'Fine'","messageType":"REQ_NOT_FOUND","sourceId":"_4055D956-1C47-479C-B3F4-BAEB61F1C929","level":"ERROR"},{"severity":"ERROR","message":"Required dependency 'Driver' not found on node 'Should the driver be suspended?'","messageType":"REQ_NOT_FOUND","sourceId":"_8A408366-D8E9-4626-ABF3-5F69AA01F880","level":"ERROR"}],"decisionResults":[{"decisionId":"_4055D956-1C47-479C-B3F4-BAEB61F1C929","decisionName":"Fine","result":null,"messages":[{"severity":"ERROR","message":"Required dependency 'Violation' not found on node 'Fine'","messageType":"REQ_NOT_FOUND","sourceId":"_4055D956-1C47-479C-B3F4-BAEB61F1C929","level":"ERROR"}],"evaluationStatus":"SKIPPED"},{"decisionId":"_8A408366-D8E9-4626-ABF3-5F69AA01F880","decisionName":"Should the driver be suspended?","result":null,"messages":[{"severity":"ERROR","message":"Required dependency 'Driver' not found on node 'Should the driver be suspended?'","messageType":"REQ_NOT_FOUND","sourceId":"_8A408366-D8E9-4626-ABF3-5F69AA01F880","level":"ERROR"},{"severity":"ERROR","message":"Required dependency 'Driver' not found on node 'Should the driver be suspended?'","messageType":"REQ_NOT_FOUND","sourceId":"_8A408366-D8E9-4626-ABF3-5F69AA01F880","level":"ERROR"}],"evaluationStatus":"SKIPPED"}]}%`

**Comment by r00ta** [comment]
Hi @jiwonjoung , apparently your dmn model contains some errors. 
At the moment the only thing you can do to test your model is to deploy it with kogito, but we are currently working on some other solutions (also with the online editor) that will make testing much more easy

**Comment by r00ta** [comment]
Hi @jiwonjoung , if you want to quickly test your dmn model you can use the new JIT dmn service https://github.com/kiegroup/kogito-apps/tree/master/jitexecutor. 

You can run the docker image we provide with 
```
docker run -p 8080:8080 quay.io/kiegroup/kogito-jit-runner:1.2
```
and submit the request according to the readme you see in the link before. 

In the next weeks/months a new update of the online editor https://kiegroup.github.io/kogito-online/#/editor/dmn will incorporate this concept of testing and will be much easier to work with it. 

If you want to get in touch with us for a follow up feel free to join us on zulip 

I'll close the issue in the meanwhile
