### ISSUE TITLE
process instance diagram does not work: port must be in range

### ISSUE THREAD

**Issue by rbaumgar** [apache/incubator-kie-examples#634]
I deployed kogito-travel-agency/extended/travels and visas onto OpenShift 4.7 with infinispan, kafka and data-service
So far everything is working perfect. Version 1.4.1-Final

I can successful access the process diagram like described https://docs.jboss.org/kogito/release/latest/html_single/#_process_diagram
```
$ curl -X GET "http://travels-kogito-travel-agency.apps..../svg/processes/travels" -H 'content-type: application/json' -H 'accept: image/svg+xml'
```
When I try to get the process instance diagram like described
https://docs.jboss.org/kogito/release/latest/html_single/#_process_instance_diagram
```
$ curl -X GET "http://travels-kogito-travel-agency.apps..../svg/processes/travels/instances/6b29a34d-3afc-42b2-87bf-6bf66c1f2691" -H 'content-type: application/json' -H 'accept: image/svg+xml'
{"message":"port p must be in range 0 <= p <= 65535"}
```
BTW the documentation  ontains a suffix with "/nodeinstances"
```
[GET] /svg/processes/{processId}/instances/{processInstanceId}/nodeInstances
```

**Comment by vaibhavjainwiz** [comment]
Issue wasn't reproduced on 1.7. Kindly reopen it if you face this issue again.
