### ISSUE TITLE
Travel Agency Tutorial - Basic - java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by uteegozi** [apache/incubator-kie-examples#753]
when running the example as described inside the Dockerfile.jvm, the following exception happens:

Caused by: java.lang.UnsupportedClassVersionError: io/quarkus/bootstrap/logging/InitialConfigurator has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

Seems like the io.quarkus.bootstrap:quarkus-bootstrap-parent **Java version was advanced from java 8 -> java 11** and now the fabric8/java-alpine-openjdk8-jre runtime is not fitting - replacing with java-alpine-openjdk11-jre works

**Comment by ricardozanini** [comment]
@uteegozi, many thanks for letting us know. Do you think you can send a PR to replace the image? :)

**Comment by uteegozi** [comment]
@ricardozanini yes, I will open a Jira which will address the need to replace the image in ALL examples using the old java8 image. Open it as a minor task would be ok? I will assign it to another member of my team, Daniele.

**Comment by ricardozanini** [comment]
@uteegozi you can assign it to me :)

**Comment by uteegozi** [comment]
@ricardozanini Oh, already Daniele is dealing with it - hope that is ok

**Comment by ricardozanini** [comment]
Handled in https://github.com/kiegroup/kogito-examples/pull/762
