### ISSUE TITLE
ruleunit-quarkus-example - stateless sessions? How do we save the data we posted? 

### ISSUE THREAD

**Issue by maxloopinmok** [apache/incubator-kie-examples#868]
For the example ruleunit-quarkus-example, does it use stateless or stateful sessions? Based on my tests using Swagger UI, the data that are posted are not saved. How do we save the data?

**Comment by r00ta** [comment]
Hi @maxloosmu , 
I think this https://groups.google.com/g/kogito-development/c/dFrQSe__YkU/m/grOb1b_aAgAJ answers your question

**Comment by maxloopinmok** [comment]
Hi @r00ta , 
Thanks, I have another related question, but I do not have permission to post to the google groups conversation.  I'm new to Drools and Kogito, but I've briefly read this:

https://docs.kogito.kie.org/latest/html_single/#con-persistence_kogito-developing-process-services

Will either of the 4 persistence options (using Infinispan, MongoDB, Kafka Streams or PostgreSQL) be able to resolve the "working memory replication" problem mentioned in the google groups conversation?

**Comment by r00ta** [comment]
Hi @maxloosmu , nope: the persistence is only for bpmn and not for rules. Kogito does not support stateful sessions for rules yet, If your scenario is stateful, I think you should stay with the KIE Execution Server until Kogito supports that as well
