### ISSUE TITLE
Kogito Travel Agency example: data-index crashes when running docker-compose

### ISSUE THREAD

**Issue by plorent** [apache/incubator-kie-examples#889]
When running docker-compose (kogito-examples/kogito-travel-agency/extended/docker-compose) the data-index crashes with `ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): org.infinispan.commons.CacheConfigurationException: ISPN004030: Cannot enable authentication without specifying either a username, a token, a client Subject or a CallbackHandler`. How can we resolve this?

**Comment by ricardozanini** [comment]
@cristianonicolai any thoughts?

**Comment by cristianonicolai** [comment]
@plorent thanks for reporting this, I created a PR for fixing the examples but you can fix it manually for now by simply adding:
`QUARKUS_INFINISPAN_CLIENT_USE_AUTH: "false"` to Data Index environment variables inside the docker compose file.

**Comment by plorent** [comment]
Thanks @cristianonicolai - closing this issue.
