### ISSUE TITLE
Support for spring webflux

### ISSUE THREAD

**Issue by himanshumps** [apache/incubator-kie-examples#918]
Kogito currently supports spring mvc and not spring webflux. Is there any plan to support that ?

I am guessing if it supports Quarkus, it should not be difficult to support webflux as well.

Any pointers on how it can be achieved ?

**Comment by ricardozanini** [comment]
Hi @himanshumps!

We don't have plans to support Spring Webflux, but I understand it's fairly simple to implement yourself if you disable the REST creation and call the APIs directly (summon @evacchi)

**Comment by himanshumps** [comment]
I think I am getting the gist of it and should be able to model it for spring webflux as per the needs. The code generated by the maven plugin gave me a way to achieve it. I am closing this issue.

**Comment by ricardozanini** [comment]
Please share with us the outcome. :)

I can see a blog post on our [website](https://blog.kie.org) about this use case.

**Comment by himanshu-gupta01** [comment]
> Please share with us the outcome. :)
> 
> I can see a blog post on our [website](https://blog.kie.org) about this use case.
@ricardozanini 
Are we talking about this link ?

https://blog.kie.org/2021/09/kogito-api-incubation.html

**Comment by himanshu-gupta01** [comment]
@ricardozanini Not able to find any reference on blog. Can you point me to exact blog post?

**Comment by himanshu-gupta01** [comment]
Are we talking about this?

https://blog.kie.org/2021/09/kogito-api-incubation.html

**Comment by ricardozanini** [comment]
@himanshu-gupta01, I meant that you could write a blog post about integrating webflux as soon as you accomplish it.

And yes, this article you linked can help you put things together. :)

Thanks!
