### ISSUE TITLE
Create rule programmatically rather than from DRL file

### ISSUE THREAD

**Issue by himanshumps** [apache/incubator-kie-examples#922]
I looked at all the examples and couldn't find any way to generate the DRL or rules using the Fluent or DSL API .. Is there any way I can take a json file which has the rules and convert it into DRL file ?

Any test case or sample would be highly appreciated

**Comment by evacchi** [comment]
DRL rules are currently supposed to be present in your project and processed at build-time, thus it would not be currently possible to synthesize rules on the fly.
