### ISSUE TITLE
serverless-workflow-error-quarkus compilation error

### ISSUE THREAD

**Issue by antmendoza** [apache/incubator-kie-examples#967]
After compiling the whole `kogito-examples` project I have tried to run `mvn clean package quarkus:dev` (into serverless-workflow-error-quarkus) and I've got the following error:

```
[FATAL] Non-resolvable parent POM for org.kie.kogito.examples:serverless-workflow-error-quarkus:2.0.0-SNAPSHOT: Could not find artifact org.kie.kogito.examples:kogito-examples:pom:2.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 11
```

I've changed the parent pom version to 1.12.0.Final, and after running `mvn clean package quarkus:dev` again I've got:

```
[INFO] Exact method isEven match not found with parameters [class java.lang.String], searching for a suitable candidate
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.138 s
[INFO] Finished at: 2021-11-03T22:32:56+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.3.0.Final:build (default) on project serverless-workflow-error-quarkus: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor#generateModel threw an exception: org.kie.kogito.codegen.process.ProcessCodegenException: Error while elaborating process id = "error", packageName = "org.kie.kogito.serverless": Invalid work item "isEven": could not find a method called "isEven" in class "org.kie.kogito.examples.EvenService" with proper arguments "{number=java.lang.String}", error "java.lang.NoSuchMethodException: No suitable method found with name isEven"


```

**Comment by fjtirado** [comment]
you need latest version of kogito-runtimes main branch in order serverless-workflow-error-quarkus to work
See commit 8fbd991ef6d50265fafaf63bf975f7c78716b246

**Comment by antmendoza** [comment]
ok I didn't know that,  sorry!! 

I will give it a try, thank you!!!

**Comment by antmendoza** [comment]
the issue happens in the "stable" branch, where the version of the parent pom (kogito-examples) is 1.12.0.Final.
serverless-workflow-error-quarkus is expecting the parent pom to be in 2.0.0-SNAPSHOT

**Comment by fjtirado** [comment]
yes, you need to use main

**Comment by antmendoza** [comment]
you can close this if you think that this is not an issue, 

just be aware that this [article](https://blog.kie.org/2021/11/error-handling-in-serverless-workflow.html) has a link pointing to the stable branch 

thank you for the clarification  🙂
